/**
 * 투표 세션 관리 유틸리티
 * 세션 생성, 검증, 자동 비활성화 등 안정적인 세션 관리
 */

import { PrismaClient } from '@prisma/client';
import { getKoreaTime, getThisWeekMonday, getNextWeekMonday, getVoteSessionSundayDeadline, getKstDateKey, isSessionExpired, aggregateVotesByWeekday, type WeekdayKey } from './voteUtils';

const prisma = new PrismaClient();

async function regenerateAutoGamesForSession(sessionId: number, weekStartDate: Date): Promise<void> {
  const weekStart = new Date(weekStartDate);
  const weekEnd = new Date(weekStart);
  weekEnd.setDate(weekEnd.getDate() + 6);

  await prisma.game.deleteMany({
    where: {
      autoGenerated: true,
      date: { gte: weekStart, lte: weekEnd }
    }
  });

  const votes = await prisma.vote.findMany({
    where: { voteSessionId: sessionId },
    include: { user: { select: { name: true } } }
  });

  const { counts, participantsByDay } = aggregateVotesByWeekday(votes);

  const maxVotes = Math.max(...Object.values(counts));
  if (maxVotes <= 0) {
    console.log('ℹ️ 자동경기 생성 생략: 유효 요일 득표 없음', { sessionId });
    return;
  }

  const topDays = (Object.keys(counts) as WeekdayKey[]).filter((day) => counts[day] === maxVotes);
  const dayOffset: Record<WeekdayKey, number> = { MON: 0, TUE: 1, WED: 2, THU: 3, FRI: 4, SAT: 5, SUN: 6 };
  const creatorId = votes[0]?.userId ?? 1;

  for (const day of topDays) {
    const gameDate = new Date(weekStart);
    gameDate.setDate(weekStart.getDate() + dayOffset[day]);
    gameDate.setHours(0, 1, 0, 0);

    await prisma.game.create({
      data: {
        date: gameDate,
        time: '미정',
        location: '미정',
        eventType: '미정',
        gameType: '미정',
        mercenaryCount: 0,
        memberNames: '[]',
        selectedMembers: JSON.stringify(participantsByDay[day] || []),
        autoGenerated: true,
        confirmed: false,
        createdById: creatorId
      }
    });
  }
}

/**
 * 만료된 세션 자동 비활성화
 */
export async function deactivateExpiredSessions(): Promise<number> {
  try {
    const koreaTime = getKoreaTime();
    const activeSessions = await prisma.voteSession.findMany({
      where: { isActive: true }
    });
    
    let deactivatedCount = 0;
    
    for (const session of activeSessions) {
      const sessionStart = new Date(session.weekStartDate);
      const shouldCloseByWeekStart = koreaTime >= sessionStart;
      if (isSessionExpired(session) || shouldCloseByWeekStart) {
        await prisma.voteSession.update({
          where: { id: session.id },
          data: {
            isActive: false,
            isCompleted: true,
            endTime: session.endTime ?? getVoteSessionSundayDeadline(sessionStart)
          }
        });
        await regenerateAutoGamesForSession(session.id, new Date(session.weekStartDate));
        console.log(`✅ 만료된 세션 비활성화: ${session.id}`);
        deactivatedCount++;
      }
    }
    
    return deactivatedCount;
  } catch (error) {
    console.error('❌ 만료된 세션 비활성화 오류:', error);
    throw error;
  }
}

/**
 * 중복 활성 세션 처리 (가장 최신 세션만 활성 유지)
 */
export async function ensureSingleActiveSession(): Promise<void> {
  try {
    const activeSessions = await prisma.voteSession.findMany({
      where: { isActive: true },
      orderBy: { id: 'desc' }
    });
    
    if (activeSessions.length > 1) {
      const sessionsToDeactivate = activeSessions.slice(1);
      for (const session of sessionsToDeactivate) {
        await prisma.voteSession.update({
          where: { id: session.id },
          data: { isActive: false, isCompleted: true }
        });
        console.log(`✅ 중복 활성 세션 비활성화: ${session.id}`);
      }
    }
  } catch (error) {
    console.error('❌ 중복 활성 세션 처리 오류:', error);
    throw error;
  }
}

/**
 * 활성 세션 조회 (안전한 조회)
 */
export async function getActiveSession(includeVotes: boolean = true) {
  try {
    // 먼저 만료된 세션 비활성화
    await deactivateExpiredSessions();
    
    // 중복 활성 세션 처리
    await ensureSingleActiveSession();
    
    // 활성 세션 조회
    const activeSession = await prisma.voteSession.findFirst({
      where: { 
        isActive: true,
        isCompleted: false
      },
      include: includeVotes ? {
        votes: {
          include: {
            user: {
              select: { id: true, name: true }
            }
          }
        }
      } : undefined,
      orderBy: { createdAt: 'desc' }
    });
    
    return activeSession;
  } catch (error) {
    console.error('❌ 활성 세션 조회 오류:', error);
    throw error;
  }
}

/**
 * 다음주 세션 생성 (안전한 생성)
 */
export async function createNextWeekSession(): Promise<any> {
  try {
    const koreaTime = getKoreaTime();
    const thisWeekMonday = getThisWeekMonday(koreaTime);
    const nextWeekMonday = getNextWeekMonday(koreaTime);
    const nextWeekSundayDeadline = getVoteSessionSundayDeadline(nextWeekMonday);
    
    // 의견수렴기간 시작일은 이번주 월요일 00:01
    const discussionStartTime = new Date(thisWeekMonday);
    discussionStartTime.setHours(0, 1, 0, 0);
    
    const targetWeekKey = getKstDateKey(nextWeekMonday);
    const aroundStart = new Date(nextWeekMonday.getTime() - 36 * 60 * 60 * 1000);
    const aroundEnd = new Date(nextWeekMonday.getTime() + 36 * 60 * 60 * 1000);
    const candidates = await prisma.voteSession.findMany({
      where: {
        weekStartDate: {
          gte: aroundStart,
          lte: aroundEnd
        }
      },
      orderBy: { id: 'desc' }
    });
    const existingNextWeekSession = candidates.find((s) => getKstDateKey(new Date(s.weekStartDate)) === targetWeekKey);
    
    if (existingNextWeekSession) {
      console.log(`ℹ️ 다음주 세션이 이미 존재합니다: ${existingNextWeekSession.id}`);
      return existingNextWeekSession;
    }

    // 기존 활성 세션이 있는지 확인
    const activeSession = await prisma.voteSession.findFirst({
      where: {
        isActive: true,
        isCompleted: false,
      },
    });

    // 새로운 투표 세션 생성
    // 이미 다른 활성 세션이 있으면 "대기(비활성)"로 생성하여 누락을 방지한다.
    const newSession = await prisma.voteSession.create({
      data: {
        weekStartDate: nextWeekMonday,
        startTime: discussionStartTime,
        endTime: nextWeekSundayDeadline,
        isActive: !activeSession,
        isCompleted: false,
      },
    });
    
    console.log(`🎉 새로운 투표 세션 생성 완료: ${newSession.id} (${newSession.weekStartDate.toLocaleDateString('ko-KR')}) isActive=${newSession.isActive}`);
    
    return newSession;
  } catch (error) {
    console.error('❌ 다음주 세션 생성 오류:', error);
    throw error;
  }
}

/**
 * 세션 상태 검증 및 자동 수정
 */
export async function validateAndFixSessionState(): Promise<void> {
  try {
    // 만료된 세션 비활성화
    await deactivateExpiredSessions();
    
    // 중복 활성 세션 처리
    await ensureSingleActiveSession();

    // 다음주 세션이 누락되지 않도록 항상 보장
    await createNextWeekSession();

    // 활성 세션이 없다면 대기 중인 최신 세션을 활성화
    const activeSession = await prisma.voteSession.findFirst({
      where: { isActive: true, isCompleted: false },
      orderBy: { createdAt: 'desc' }
    });
    if (!activeSession) {
      const pendingSession = await prisma.voteSession.findFirst({
        where: { isActive: false, isCompleted: false },
        orderBy: [
          { weekStartDate: 'asc' },
          { id: 'desc' }
        ]
      });

      if (pendingSession) {
        await prisma.voteSession.update({
          where: { id: pendingSession.id },
          data: { isActive: true }
        });
        console.log(`✅ 대기 세션 자동 활성화: ${pendingSession.id}`);
      }
    }
    
    console.log('✅ 세션 상태 검증 완료');
  } catch (error) {
    console.error('❌ 세션 상태 검증 오류:', error);
    throw error;
  }
}

