// 공통 API 클라이언트 (프론트 전역에서 사용)
import { API_ENDPOINTS } from '../constants';
import { getApiBaseUrl, getApiUrl } from '../config/api';

// ===== 타입 =====
export type Role = 'SUPER_ADMIN' | 'ADMIN' | 'MEMBER' | 'GUEST';
export type MemberStatus = 'ACTIVE' | 'INACTIVE' | 'SUSPENDED' | 'DELETED';

export interface Member {
  id: number;
  name: string;
  email?: string;
  role?: Role;
  status?: MemberStatus;
}

export interface Game {
  id: number;
  date: string;
  time?: string;
  location?: string;
  gameType?: string;
  autoGenerated?: boolean;
  confirmed?: boolean;
  memberNames?: string[] | string;
}

export interface StatsSummary {
  totalMembers: number;
  confirmedGames: number;
  totalGames: number;
  activeVotePeriod?: string;
}

// ===== 토큰 유틸 =====
export const getValidToken = (): string | null => {
  const s = typeof window !== 'undefined' ? window.sessionStorage.getItem('token') : null;
  const l = typeof window !== 'undefined' ? window.localStorage.getItem('token') : null;
  return s || l;
};

const authHeaders = () => {
  const token = getValidToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
};

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const request = async <T = any>(path: string, init: RequestInit = {}): Promise<T> => {
  const url = await getApiUrl(path);
  const method = String(init.method || 'GET').toUpperCase();
  const maxAttempts = method === 'GET' ? 2 : 1;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 15000);

    try {
      const res = await fetch(url, {
        headers: { 'Content-Type': 'application/json', ...authHeaders(), ...(init.headers || {}) },
        ...init,
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!res.ok) {
        const errorText = await res.text();
        let errorData;
        try {
          errorData = JSON.parse(errorText);
        } catch {
          errorData = { error: errorText || '요청 처리 중 오류가 발생했습니다.' };
        }
        const error = new Error(errorData.error || errorData.message || '요청 처리 중 오류가 발생했습니다.');
        (error as any).response = { status: res.status, data: errorData };

        const retryable = method === 'GET' && attempt < maxAttempts && res.status >= 500;
        if (retryable) {
          await delay(350);
          continue;
        }
        throw error;
      }
      const ct = res.headers.get('content-type') || '';
      return (ct.includes('application/json') ? (await res.json()) : (await res.text())) as T;
    } catch (error: any) {
      clearTimeout(timeoutId);

      const isTimeout = error.name === 'AbortError' || String(error.message || '').includes('aborted');
      const isNetwork = String(error.message || '').includes('Failed to fetch') || String(error.message || '').includes('NetworkError');
      const retryable = method === 'GET' && attempt < maxAttempts && (isTimeout || isNetwork);
      if (retryable) {
        await delay(350);
        continue;
      }

      if (isTimeout) {
        const timeoutError = new Error('요청 시간이 초과되었습니다. 네트워크 연결을 확인해주세요.');
        (timeoutError as any).response = { status: 408, data: { error: '요청 시간 초과' } };
        throw timeoutError;
      }

      if (isNetwork) {
        const networkError = new Error('네트워크 오류가 발생했습니다. 서버 연결을 확인해주세요.');
        (networkError as any).response = { status: 0, data: { error: '네트워크 오류' } };
        throw networkError;
      }

      throw error;
    }
  }
  throw new Error('요청 처리 중 알 수 없는 오류가 발생했습니다.');
};

// ===== 인증 =====
export const login = (email: string, password: string) =>
  request<{ token: string; user: any }>('/login', { method: 'POST', body: JSON.stringify({ email, password }) });

export const register = async (data: { name: string; email: string; password: string; phone?: string }) => {
  const body = { name: data.name, email: data.email, password: data.password, phone: data.phone || null };
  console.log('🔍 register API 호출 시작:', { 
    url: '/register', 
    body: { ...body, password: body.password ? '***' : undefined }
  });
  
  try {
    const url = await getApiUrl('/register');
    console.log('🔍 register API URL:', url);
    
    const result = await request<{ token?: string; user: any; message?: string }>('/register', { 
      method: 'POST', 
      body: JSON.stringify(body) 
    });
    
    console.log('✅ register API 응답 성공:', result);
    return result;
  } catch (error) {
    console.error('❌ register API 오류:', error);
    throw error;
  }
};

export const updateProfile = (data: Partial<Member>) =>
  request('/profile', { method: 'PUT', body: JSON.stringify(data) });

export const changePassword = (newPassword: string) =>
  request('/change-password', {
    method: 'PUT',
    body: JSON.stringify({ newPassword }),
  });

export const getProfile = () => request('/profile');

// ===== 멤버 관리 =====
export const getMemberStats = () => request('/activity-analysis');

export const updateMember = (memberId: number, data: Partial<Member>) =>
  request(`/members/${memberId}`, { method: 'PUT', body: JSON.stringify(data) });

export const deleteMember = (memberId: number) =>
  request(`/members/${memberId}`, { method: 'DELETE' });

export const resetMemberPassword = (memberId: number) =>
  request(`/members/${memberId}/reset-password`, { method: 'POST' });

export const askChatbot = (question: string) =>
  request('/chatbot/query', { method: 'POST', body: JSON.stringify({ question }) });

// ===== 투표/일정 =====
export const getUnifiedVoteDataNew = () => request('/unified-vote-data');

export const getAdminVoteSessionsSummary = () => request('/votes/sessions/summary');

export const getSavedVoteResults = (sessionId: number) => 
  request(`/votes/results?sessionId=${sessionId}`);

export const aggregateAndSaveVoteResults = (payload: any) =>
  request('/votes/aggregate/save', { method: 'POST', body: JSON.stringify(payload) });

export const closeVoteSession = (id: number) =>
  request(`/vote-sessions/${id}/close`, { method: 'POST' });

export const resumeVoteSession = (id: number) =>
  request(`/vote-sessions/${id}/resume`, { method: 'POST' });

export const deleteVoteSession = (id: number) =>
  request(`/vote-sessions/${id}`, { method: 'DELETE' });

export const bulkDeleteVoteSessions = (ids: number[]) =>
  request('/cleanup-duplicate-sessions', { method: 'POST', body: JSON.stringify({ ids }) });

export const renumberVoteSessions = () =>
  request('/cleanup-duplicate-sessions', { method: 'POST' });

export const cleanupDuplicateSessions = () =>
  request('/cleanup-duplicate-sessions', { method: 'POST' });

export const startWeeklyVote = () => request('/start-weekly-vote', { method: 'POST' });

// 사용자 투표 삭제 (재투표용)
export const deleteVote = (userId: number) =>
  request(`/votes/${userId}`, { method: 'DELETE' });

// ===== 기타 유틸 =====
export const apiGet = request;