import React, { useState } from 'react';
import {
  Box,
  Button,
  Table,
  TableContainer,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  IconButton,
  HStack,
  VStack,
  Text,
  useDisclosure,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  ModalCloseButton,
  FormControl,
  FormLabel,
  Input,
  Select,
  useToast,
  Tooltip,
  Flex,
  Icon,
  Stack
} from '@chakra-ui/react';
import { AddIcon, DeleteIcon } from '@chakra-ui/icons';
import { LuCalendarCheck, LuCalendarPlus, LuCalendarX, LuMapPin, LuPencil, LuTrash2, LuUsers } from 'react-icons/lu';
import { AdminEmptyState, AdminPageHeader, AdminPanel, DateBlock, LiveDot, PanelHeader, PitchLines, StatBlock, StatStrip, StatusBadge } from './admin/MatchDay';
import { GRADIENTS } from '../constants/designTokens';
import { getValidToken } from '../api/auth';
import { emitGameConfirmed, emitDataRefreshNeeded, emitAlert } from '../utils/eventBus';
import { showGameConfirmationNotification } from '../utils/pushNotifications';
import { getApiUrl } from '../config/api';

/** 경기 목록 표시용 날짜 파싱(yyyy.mm.dd / ISO 등) — 정렬 실패 시 0 */
function parseGameDateMs(game: { date?: string }): number {
  if (!game?.date) return 0;
  const s = String(game.date);
  const m = s.match(/(\d{4})\.(\d{2})\.(\d{2})/);
  if (m) {
    const t = new Date(parseInt(m[1], 10), parseInt(m[2], 10) - 1, parseInt(m[3], 10)).getTime();
    return Number.isNaN(t) ? 0 : t;
  }
  const t = new Date(s).getTime();
  return Number.isNaN(t) ? 0 : t;
}

interface Game {
  id: number;
  date: string;
  time?: string;
  location: string;
  locationAddress?: string; // 장소 주소 (신주소)
  locationLatitude?: number | null;
  locationLongitude?: number | null;
  eventType?: '매치' | '회식' | '자체';
  mercenaryCount: number;
  memberNames: string[];
  selectedMembers?: string[];
  createdById: number;
  createdAt: string;
  updatedAt: string;
  createdBy?: {
    id: number;
    name: string;
  };
  attendances?: any[];
  autoGenerated?: boolean; // 자동 생성된 경기임을 표시하는 필드
}

interface GameManagementProps {
  games: Game[];
  onGamesChange: (games: Game[]) => void;
  userList: any[]; // 회원 목록 추가
  onGameDataChanged?: () => void; // 경기 데이터 변경 시 호출할 콜백
}

export default function GameManagement({ games, onGamesChange, userList, onGameDataChanged }: GameManagementProps) {
  console.log('=== GameManagement 컴포넌트 렌더링 ===');
  console.log('GameManagement - 받은 games prop:', games);
  console.log('GameManagement - games 길이:', games?.length);
  console.log('GameManagement - games 타입:', typeof games);
  console.log('GameManagement - games가 배열인가:', Array.isArray(games));
  console.log('GameManagement - games 내용:', JSON.stringify(games, null, 2));

  const brandBlue = '#004ea8';

  // 중복 제거: 같은 날짜에 확정일정이 있으면 자동생성일정 제거
  const filteredGames = React.useMemo(() => {
    if (!games || !Array.isArray(games)) return [];
    
    console.log('🔍 GameManagement 필터링 시작:', {
      totalGames: games.length,
      games: games.map(game => ({
        id: game.id,
        date: game.date,
        autoGenerated: game.autoGenerated,
        confirmed: game.confirmed
      }))
    });
    
    const confirmedGames = games.filter(game => !game.autoGenerated);
    const autoGeneratedGames = games.filter(game => game.autoGenerated);
    
    console.log('🔍 게임 분류:', {
      confirmed: confirmedGames.length,
      autoGenerated: autoGeneratedGames.length,
      confirmedGames: confirmedGames.map(g => ({ id: g.id, date: g.date })),
      autoGeneratedGames: autoGeneratedGames.map(g => ({ id: g.id, date: g.date }))
    });
    
    // 확정일정이 있는 날짜들 추출
    const confirmedDates = new Set(
      confirmedGames.map(game => {
        if (!game.date || typeof game.date !== 'string') return null;
        const dateMatch = game.date.match(/(\d{4})\.(\d{2})\.(\d{2})/);
        return dateMatch ? `${dateMatch[1]}.${dateMatch[2]}.${dateMatch[3]}` : null;
      }).filter(Boolean)
    );
    
    console.log('🔍 확정일정 날짜들:', Array.from(confirmedDates));
    
    // 자동생성일정 필터링 임시 비활성화 (디버깅용)
    const filteredAutoGenerated = autoGeneratedGames;
    
    console.log('⚠️ 자동생성일정 필터링 비활성화됨 - 모든 자동생성일정 표시');
    
    /*
    // 자동생성일정 중에서 확정일정이 있는 날짜는 제외
    const filteredAutoGenerated = autoGeneratedGames.filter(game => {
      if (!game.date || typeof game.date !== 'string') return false;
      const dateMatch = game.date.match(/(\d{4})\.(\d{2})\.(\d{2})/);
      const gameDate = dateMatch ? `${dateMatch[1]}.${dateMatch[2]}.${dateMatch[3]}` : null;
      const shouldInclude = gameDate && !confirmedDates.has(gameDate);
      
      console.log('🔍 자동생성일정 필터링:', {
        gameId: game.id,
        gameDate: game.date,
        extractedDate: gameDate,
        shouldInclude,
        reason: shouldInclude ? '포함' : '제외 (확정일정과 중복)'
      });
      
      return shouldInclude;
    });
    */
    
    const result = [...confirmedGames, ...filteredAutoGenerated];
    // 최신 경기일이 위로 오도록 정렬
    result.sort((a, b) => parseGameDateMs(b) - parseGameDateMs(a));
    console.log('🔍 최종 필터링 결과:', {
      original: games.length,
      confirmed: confirmedGames.length,
      autoGenerated: autoGeneratedGames.length,
      filteredAutoGenerated: filteredAutoGenerated.length,
      final: result.length,
      finalGames: result.map(g => ({ id: g.id, date: g.date, autoGenerated: g.autoGenerated }))
    });
    
    return result;
  }, [games]);
  const { isOpen, onOpen, onClose } = useDisclosure();
  const { isOpen: isDeleteOpen, onOpen: onDeleteOpen, onClose: onDeleteClose } = useDisclosure();
  const [editingGame, setEditingGame] = useState<Game | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<Game | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [formData, setFormData] = useState({
    date: '',
    time: '',
    location: '',
    locationBase: '', // 카카오맵 검색용 원래 장소명
    locationDetail: '', // 세부 장소 (예: 1구장)
    locationAddress: '', // 장소 주소 (신주소)
    locationLatitude: null as number | null,
    locationLongitude: null as number | null,
    eventType: '자체' as '매치' | '회식' | '자체',
    mercenaryCount: 0,
    memberNames: ['']
  });
  
  // 선택된 회원들을 별도로 관리
  const [selectedMembers, setSelectedMembers] = useState<string[]>([]);
  
  // 컴포넌트 마운트 시 경기 목록 불러오기 (AdminPageNew에서 이미 로드됨)
  // React.useEffect(() => {
  //   fetchGames();
  // }, []);

  // 투표재개 시 자동생성 일정 제거
  React.useEffect(() => {
    const handleVoteSessionResumed = () => {
      console.log('🔄 투표재개 이벤트 수신 - 자동생성 일정 제거');
      const updatedGames = games.filter(game => !game.autoGenerated);
      onGamesChange(updatedGames);
      console.log('✅ 자동생성 일정 제거 완료:', updatedGames.length, '개 남음');
    };

    // 이벤트 리스너 등록
    window.addEventListener('voteSessionResumed', handleVoteSessionResumed);
    
    // 컴포넌트 마운트 시에도 자동생성 일정 체크
    const autoGeneratedGames = games.filter(game => game.autoGenerated);
    if (autoGeneratedGames.length > 0) {
      console.log('🔍 컴포넌트 마운트 시 자동생성 일정 발견:', autoGeneratedGames.length, '개');
      // 투표 세션이 활성화되어 있다면 자동생성 일정 제거
      const hasActiveVoteSession = window.location.href.includes('vote-results') || 
                                   document.querySelector('[data-vote-active="true"]');
      if (hasActiveVoteSession) {
        console.log('🔄 활성 투표 세션 감지 - 자동생성 일정 제거');
        const updatedGames = games.filter(game => !game.autoGenerated);
        onGamesChange(updatedGames);
      }
    }
    
    return () => {
      window.removeEventListener('voteSessionResumed', handleVoteSessionResumed);
    };
  }, [games, onGamesChange]);
  
  // 경기 목록 불러오기
  const fetchGames = React.useCallback(async () => {
    try {
      const token = getValidToken();
      const gamesUrl = await getApiUrl('/games?includeAutoGenerated=true');
      const response = await fetch(gamesUrl, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      if (response.ok) {
        const gamesData = await response.json();
        
        // 실제 데이터베이스의 경기 데이터 사용
        if (Array.isArray(gamesData) && gamesData.length > 0) {
          console.log('🔄 실제 경기 데이터 로드 완료:', gamesData.length, '개');
          
          // 자동 생성된 경기인지 확인 (백엔드에서 받은 autoGenerated 값 사용)
          const processedGames = gamesData.map((game: any) => {
            const rawMemberNames = Array.isArray(game.memberNames)
              ? game.memberNames
              : (typeof game.memberNames === 'string'
                ? (() => { try { return JSON.parse(game.memberNames); } catch { return []; } })()
                : []);
            const rawSelectedMembers = Array.isArray(game.selectedMembers)
              ? game.selectedMembers
              : (typeof game.selectedMembers === 'string'
                ? (() => { try { return JSON.parse(game.selectedMembers); } catch { return []; } })()
                : []);
            const selectedSet = new Set<string>(rawSelectedMembers.filter(Boolean));
            const otherCount = rawMemberNames.filter((n: any) => {
              if (typeof n !== 'string') return false;
              const t = n.trim();
              if (!t) return false;
              if (t.startsWith('용병')) return false;
              if (selectedSet.has(t)) return false;
              return true;
            }).length;
            const computedTotal = (Number(game.mercenaryCount) || 0) + selectedSet.size + otherCount;

            return {
              ...game,
              autoGenerated: game.autoGenerated === true,
              time: game.time || '',
              location: game.location || '장소 미정',
              eventType: game.eventType || '자체',
              totalParticipantCount: computedTotal
            };
          });
          
          onGamesChange(processedGames);
          console.log('✅ 경기 데이터 처리 완료');
          console.log('📊 첫 번째 경기 totalParticipantCount:', processedGames[0]?.totalParticipantCount);
          console.log('📊 첫 번째 경기 상세:', processedGames[0]);
        } else {
          console.log('📝 등록된 경기가 없습니다');
          onGamesChange([]);
        }
      }
    } catch (error) {
      console.error('경기 목록 불러오기 오류:', error);
      onGamesChange([]);
    }
  }, [onGamesChange]);

  React.useEffect(() => {
    fetchGames();
  }, [fetchGames]);
  
  // 실제 회원 기준으로 회원 수 계산 (중복 제거 및 유효성 검사)
  const getUniqueMemberCount = React.useCallback(() => {
    const actualMemberNames = (userList || []).map((m: any) => m.name);
    const filtered = (selectedMembers || []).filter((name: string) => actualMemberNames.includes(name));
    const unique = Array.from(new Set(filtered));
    return unique.length;
  }, [selectedMembers, userList]);
  
  // 카카오맵 검색 관련 상태
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<any[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [showSearchResults, setShowSearchResults] = useState(false);
  
  const toast = useToast();

  const handleAddGame = () => {
    setEditingGame(null);
    setSelectedMembers([]); // 선택된 회원 초기화
    setFormData({
      date: '',
      time: '',
      location: '',
      locationBase: '',
      locationDetail: '',
      locationAddress: '',
      locationLatitude: null,
      locationLongitude: null,
      eventType: '자체',
      mercenaryCount: 0,
      memberNames: ['']
    });
    onOpen();
  };

  const handleEditGame = (game: Game) => {
    console.log('🎯 handleEditGame 호출 (v2):', game);
    console.log('🎯 game.autoGenerated:', game.autoGenerated);
    
    // autoGenerated 속성을 명시적으로 설정
    const gameWithAutoGenerated = {
      ...game,
      autoGenerated: game.autoGenerated === true // 명시적으로 boolean으로 변환
    };
    
    setEditingGame(gameWithAutoGenerated);
    console.log('🎯 setEditingGame 완료 (v2):', gameWithAutoGenerated);
    console.log('🎯 autoGenerated 확인:', gameWithAutoGenerated.autoGenerated);
    
    // 날짜를 YYYY-MM-DD 형식으로 변환 (KST 로컬 날짜 기준)
    const gameDate = new Date(game.date);
    const _fy = gameDate.getFullYear();
    const _fm = String(gameDate.getMonth() + 1).padStart(2, '0');
    const _fd = String(gameDate.getDate()).padStart(2, '0');
    const formattedDate = `${_fy}-${_fm}-${_fd}`;
    
    // 기존 selectedMembers와 memberNames를 분리하여 로드
    const existingSelectedMembers = parseMemberNames(game.selectedMembers || []);
    const allMemberNames = parseMemberNames(game.memberNames);
    
    // selectedMembers에 없는 것들만 수기입력으로 분리
    const existingManualMembers = allMemberNames.filter(name => 
      !existingSelectedMembers.includes(name) && 
      !name.startsWith('용병') // 용병도 제외
    );
    
    setSelectedMembers(existingSelectedMembers);
    
    // location에서 세부 장소 분리 (예: "천안풋살 1구장" -> "천안풋살", "1구장")
    let locationBase = '';
    let locationDetail = '';
    if (game.location && !game.autoGenerated && game.location !== '미정') {
      // 기존 데이터에서 세부 장소가 포함되어 있을 수 있으므로 파싱
      // 간단한 로직: 마지막 공백 이후를 세부 장소로 간주 (더 정확한 파싱은 나중에 개선 가능)
      const locationParts = game.location.split(' ');
      if (locationParts.length > 1) {
        // 마지막 부분이 세부 장소일 가능성
        locationBase = locationParts.slice(0, -1).join(' ');
        locationDetail = locationParts[locationParts.length - 1];
      } else {
        locationBase = game.location;
        locationDetail = '';
      }
    }
    
    setFormData({
      date: formattedDate,
      time: (game.autoGenerated && game.time === '미정') ? '' : (game.time || ''), // 자동생성된 게임의 "미정" 시간은 빈 문자열로 처리
      location: (game.autoGenerated && game.location === '미정') ? '' : game.location, // 자동생성된 게임의 "미정" 장소는 빈 문자열로 처리
      locationBase: locationBase,
      locationDetail: locationDetail,
      locationAddress: game.locationAddress || '', // 주소 정보
      locationLatitude: game.locationLatitude ?? null,
      locationLongitude: game.locationLongitude ?? null,
      eventType: (game.autoGenerated && (game as any).eventType === '미정') ? '자체' : (game.eventType || '자체'), // 타입 가드
      mercenaryCount: game.mercenaryCount || 0,
      memberNames: existingManualMembers.length > 0 ? existingManualMembers : ['']
    });
    onOpen();
  };

  const handleDeleteGame = async (id: number | string) => {
    try {
      // 통일 유틸로 토큰 확보
      const token = getValidToken();

      // ID 형식 정리 - 최종 강력한 파싱
      let gameId: number;
      
      console.log('🔍 삭제 원본 ID 분석:', { 
        originalId: id, 
        type: typeof id,
        stringValue: id.toString()
      });
      
      if (typeof id === 'number') {
        gameId = id;
      } else {
        // 문자열인 경우 :1, :0 등 모든 접미사 제거 후 숫자만 추출
        let cleanIdStr = id.toString();
        
        // :1, :0 등 콜론 접미사 제거
        if (cleanIdStr.includes(':')) {
          cleanIdStr = cleanIdStr.split(':')[0];
        }
        
        // 모든 비숫자 문자 제거
        cleanIdStr = cleanIdStr.replace(/[^0-9]/g, '');
        
        gameId = parseInt(cleanIdStr);
        
        console.log('🔧 삭제 ID 파싱 과정:', {
          original: id,
          afterColonRemoval: cleanIdStr,
          finalGameId: gameId
        });
      }
      
      // 유효한 ID인지 확인 (1-99999999 범위로 확장)
      if (isNaN(gameId) || gameId <= 0 || gameId > 99999999) {
        console.error('❌ 유효하지 않은 게임 ID:', { 
          originalId: id, 
          type: typeof id,
          gameId 
        });
        throw new Error(`유효하지 않은 게임 ID: ${id}`);
      }
      
      console.log('✅ 최종 파싱된 삭제 게임 ID:', { originalId: id, gameId });
      
      // 실제 게임 객체에서 ID 재확인
      const actualGame = games.find(g => {
        // 원본 ID와 비교
        if (g.id === id) return true;
        // 파싱된 ID와 비교
        if (typeof g.id === 'number' && g.id === gameId) return true;
        // 문자열 ID인 경우 파싱해서 비교
        if (typeof g.id === 'string') {
          const parsedGameId = parseInt(g.id.replace(/[^0-9]/g, ''));
          if (parsedGameId === gameId) return true;
        }
        return false;
      });
      
      if (actualGame) {
        console.log('🔍 실제 게임 객체 ID:', actualGame.id);
        // 실제 게임 객체의 ID가 숫자이고 다르면 그것을 사용
        if (typeof actualGame.id === 'number' && actualGame.id !== gameId) {
          console.log('⚠️ ID 불일치 감지, 실제 게임 ID 사용:', actualGame.id);
          gameId = actualGame.id;
        } else if (typeof actualGame.id === 'string') {
          // 문자열 ID인 경우 파싱해서 사용
          const parsedId = parseInt(actualGame.id.replace(/[^0-9]/g, ''));
          if (!isNaN(parsedId) && parsedId !== gameId) {
            console.log('⚠️ 문자열 ID 파싱, 실제 게임 ID 사용:', parsedId);
            gameId = parsedId;
          }
        }
      }
      
      console.log('🔍 경기 삭제 시도:', { 
        originalId: id, 
        gameId, 
        tokenLength: token.length 
      });

      // 자동생성 게임인지 확인
      const gameToDelete = games.find(g => {
        if (g.id === id) return true;
        if (typeof g.id === 'number' && g.id === gameId) return true;
        if (typeof g.id === 'string') {
          const parsedGameId = parseInt(g.id.replace(/[^0-9]/g, ''));
          if (parsedGameId === gameId) return true;
        }
        return false;
      });

      // 모든 게임은 백엔드에서 삭제 (자동생성 게임도 포함)
      console.log('🗑️ 게임 백엔드에서 삭제:', { gameId, isAutoGenerated: gameToDelete?.autoGenerated });
      
      const deleteUrl = await getApiUrl(`/games/${gameId}`);
      const response = await fetch(deleteUrl, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      
      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(`경기 삭제 실패: ${response.status} - ${errorData.error || response.statusText}`);
      }
      
      await fetchGames();
      // 헤더 등 전역 갱신 유도
      window.dispatchEvent(new CustomEvent('gamesChanged'));
      
      // SchedulePageV2에 경기 데이터 변경 알림
      if (onGameDataChanged) {
        onGameDataChanged();
      }
      
      toast({
        title: '경기 삭제 완료',
        description: '경기가 삭제되었습니다.',
        status: 'success',
        duration: 2000,
        isClosable: true,
      });
    } catch (error) {
      console.error('경기 삭제 오류:', error);
      toast({
        title: '경기 삭제 실패',
        description: '경기 삭제 중 오류가 발생했습니다.',
        status: 'error',
        duration: 3000,
        isClosable: true,
      });
    }
  };

  const handleConfirmDeleteGame = async () => {
    if (!deleteTarget || isDeleting) return;
    setIsDeleting(true);
    try {
      await handleDeleteGame(deleteTarget.id);
    } finally {
      setIsDeleting(false);
      onDeleteClose();
      setDeleteTarget(null);
    }
  };


  // 인원명 추가
  const addMemberName = () => {
    setFormData(prev => ({
      ...prev,
      memberNames: [...prev.memberNames, '']
    }));
  };

  // 인원명 제거
  const removeMemberName = (index: number) => {
    if (formData.memberNames.length > 1) {
      setFormData(prev => ({
        ...prev,
        memberNames: prev.memberNames.filter((_, i) => i !== index)
      }));
    }
  };

  // 인원명 변경
  const updateMemberName = (index: number, value: string) => {
    setFormData(prev => ({
      ...prev,
      memberNames: prev.memberNames.map((name, i) => i === index ? value : name)
    }));
  };

  // memberNames를 배열로 변환하는 함수
  const parseMemberNames = (memberNames: any): string[] => {
    // null, undefined 체크
    if (memberNames == null) {
      return [];
    }
    
    // 이미 배열인 경우
    if (Array.isArray(memberNames)) {
      return memberNames.filter(name => name && typeof name === 'string' && name.trim() !== '');
    }
    
    // 문자열인 경우 JSON 파싱 시도
    if (typeof memberNames === 'string') {
      try {
        const parsed = JSON.parse(memberNames);
        if (Array.isArray(parsed)) {
          return parsed.filter(name => name && typeof name === 'string' && name.trim() !== '');
        }
      } catch (error) {
        console.warn('parseMemberNames JSON 파싱 실패:', error);
      }
    }
    
    // 기본값으로 빈 배열 반환
    return [];
  };
  
  // 전체 인원 계산 - 선택된 회원, 용병, 수기입력 모두 계산
  const getTotalCount = () => {
    // 선택된 회원들 (실제 회원 목록과 매칭하여 중복 제거)
    const selectedCount = getUniqueMemberCount();
    
    // 용병 수
    const mercenaryCount = formData.mercenaryCount;
    
    // 수기입력된 회원들 (빈 문자열 제외)
    const manualCount = formData.memberNames.filter(name => 
      name.trim() !== ''
    ).length;
    
    return mercenaryCount + selectedCount + manualCount;
  };

  
  // formData 변경 시 실시간으로 인원수 업데이트
  React.useEffect(() => {
    // 인원수 변경 감지 (의존성 배열에 formData 추가)
  }, [formData.mercenaryCount, formData.memberNames]);

  // 카카오맵 장소 검색
  const searchLocation = async (query: string) => {
    if (!query.trim()) return;
    
    setIsSearching(true);
    try {
      const searchUrl = await getApiUrl(`/search-location?query=${encodeURIComponent(query)}`);
      const response = await fetch(searchUrl);
      if (response.ok) {
        const data = await response.json();
        setSearchResults(data.documents || []);
        setShowSearchResults(true);
      } else {
        toast({
          title: '검색 실패',
          description: '장소 검색에 실패했습니다.',
          status: 'error',
          duration: 3000,
          isClosable: true,
        });
      }
    } catch (error) {
      console.error('장소 검색 오류:', error);
      toast({
        title: '검색 오류',
        description: '장소 검색 중 오류가 발생했습니다.',
        status: 'error',
        duration: 3000,
        isClosable: true,
      });
    } finally {
      setIsSearching(false);
    }
  };

  // 장소 선택
  const selectLocation = (place: any) => {
    const baseLocation = place.place_name;
    const address = place.road_address_name || place.address_name || ''; // 신주소 우선, 없으면 구주소
    setFormData(prev => ({
      ...prev,
      locationBase: baseLocation,
      locationAddress: address,
      locationLatitude: Number(place.y) || null,
      locationLongitude: Number(place.x) || null,
      location: baseLocation + (prev.locationDetail ? ` ${prev.locationDetail}` : '') // 세부 장소가 있으면 함께 표시
    }));
    setSearchQuery(baseLocation);
    setShowSearchResults(false);
  };

  const handleSubmit = async () => {
    if (isSubmitting) return;
    if (!formData.date || !formData.location) {
      toast({
        title: '입력 오류',
        description: '날짜와 장소를 모두 입력해주세요.',
        status: 'error',
        duration: 2000,
        isClosable: true,
      });
      return;
    }

    // 중복 일정 체크 (자동생성된 경기는 제외)
    const selectedDate = new Date(formData.date);
    const existingGameOnDate = games.find(game => {
      const gameDate = new Date(game.date);
      return gameDate.toDateString() === selectedDate.toDateString() && 
             (!editingGame || game.id !== editingGame.id) &&
             !game.autoGenerated; // 자동생성된 경기는 중복 체크에서 제외
    });

    if (existingGameOnDate) {
      toast({
        title: '중복 일정',
        description: '해당 날짜에 이미 경기가 있습니다.',
        status: 'error',
        duration: 3000,
        isClosable: true,
      });
      return;
    }

    setIsSubmitting(true);
    try {
      if (editingGame) {
        // 자동생성된 경기를 수정하는 경우 - 일정확정 기능 수행
        if (editingGame.autoGenerated === true) {
          console.log('🎯 자동생성 경기 수정 - 일정확정 기능 수행');
          
          // 통일 유틸로 토큰 확보
          const token = getValidToken();

          // 필수 정보 확인
          if (!formData.time || !formData.location || !formData.eventType) {
            toast({
              title: '정보 부족',
              description: '시간, 장소, 이벤트 유형을 모두 입력해주세요.',
              status: 'warning',
              duration: 3000,
              isClosable: true,
            });
            return;
          }

          console.log('🎯 자동생성 경기 일정확정 시도:', { 
            gameId: editingGame.id, 
            hasToken: !!token
          });

          // 자동생성 게임을 백엔드에 새로 생성 (일정확정)
          const newGameData = {
            date: selectedDate.toISOString(),
            time: formData.time,
            location: formData.location,
            locationAddress: formData.locationAddress || '',
            locationLatitude: formData.locationLatitude,
            locationLongitude: formData.locationLongitude,
            eventType: formData.eventType || '자체',
            gameType: (formData.eventType === '매치') ? 'MATCH' : 'SELF',
            memberNames: formData.memberNames.filter(name => name.trim() !== ''),
            selectedMembers: selectedMembers,
            mercenaryCount: formData.mercenaryCount || 0,
            sendConfirmationNotification: true,
          };

          console.log('🎯 자동생성 경기 일정확정 데이터:', {
            gameId: editingGame.id,
            formData: newGameData
          });

          // ID 형식 정리 - 최종 강력한 파싱
          let gameId: number;
          
          console.log('🔍 원본 ID 분석:', { 
            originalId: editingGame.id, 
            type: typeof editingGame.id,
            stringValue: editingGame.id.toString()
          });
          
          if (typeof editingGame.id === 'number') {
            gameId = editingGame.id;
          } else {
            // 문자열인 경우 :1, :0 등 모든 접미사 제거 후 숫자만 추출
            let cleanIdStr = editingGame.id.toString();
            
            // :1, :0 등 콜론 접미사 제거
            if (cleanIdStr.includes(':')) {
              cleanIdStr = cleanIdStr.split(':')[0];
            }
            
            // 모든 비숫자 문자 제거
            cleanIdStr = cleanIdStr.replace(/[^0-9]/g, '');
            
            gameId = parseInt(cleanIdStr);
            
            console.log('🔧 ID 파싱 과정:', {
              original: editingGame.id,
              afterColonRemoval: cleanIdStr,
              finalGameId: gameId
            });
          }
          
          // 유효한 ID인지 확인 (1-99999999 범위로 확장)
          if (isNaN(gameId) || gameId <= 0 || gameId > 99999999) {
            console.error('❌ 유효하지 않은 게임 ID:', { 
              originalId: editingGame.id, 
              type: typeof editingGame.id,
              gameId 
            });
            throw new Error(`유효하지 않은 게임 ID: ${editingGame.id}`);
          }
          
          console.log('✅ 최종 파싱된 게임 ID:', { originalId: editingGame.id, gameId });
          
          // 실제 게임 객체에서 ID 재확인
          const actualGame = games.find(g => g.id === editingGame.id);
          if (actualGame) {
            console.log('🔍 실제 게임 객체 ID:', actualGame.id);
            // 실제 게임 객체의 ID가 다르면 그것을 사용
            if (typeof actualGame.id === 'number' && actualGame.id !== gameId) {
              console.log('⚠️ ID 불일치 감지, 실제 게임 ID 사용:', actualGame.id);
              gameId = actualGame.id;
            }
          }
          
          console.log('🚀 자동생성 게임 백엔드 생성 API 호출');
          const autoCreateUrl = await getApiUrl('/games');
          const response = await fetch(autoCreateUrl, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${token}`
            },
            body: JSON.stringify(newGameData)
          });

          if (!response.ok) {
            const errorData = await response.json().catch(() => ({}));
            console.error('자동생성 경기 일정확정 실패 응답:', {
              status: response.status,
              statusText: response.statusText,
              errorData
            });
            throw new Error(`일정확정 실패: ${response.status} - ${errorData.details || response.statusText}`);
          }

                const result = await response.json();
                console.log('자동생성 경기 일정확정 성공:', result);
                
                // 같은 주의 다른 자동생성 게임들 삭제는 아래에서 처리
                
                // 🔄 이벤트 시스템으로 다른 페이지에 동기화 알림
                emitGameConfirmed({
                  gameId: gameId,
                  gameData: result,
                  confirmedBy: '관리자'
                });
                emitDataRefreshNeeded('games');
                const emailWasSent = result.emailNotification?.success === true;
                emitAlert(
                  emailWasSent
                    ? '경기 일정이 확정되고 회원 알림이 발송되었습니다.'
                    : '경기 일정은 확정됐지만 이메일 발송 상태를 확인해주세요.',
                  emailWasSent ? 'success' : 'warning'
                );
                
                // 📱 푸시 알림 표시
                try {
                  await showGameConfirmationNotification({
                    gameDate: result.date || formData.date,
                    gameTime: result.time || formData.time || '미정',
                    gameLocation: result.location || formData.location || '미정',
                    gameType: result.gameType || formData.gameType || '미정'
                  });
                } catch (notificationError) {
                  console.warn('푸시 알림 표시 실패:', notificationError);
                }
                
                // 자동생성 일정 확정 후 즉시 UI 업데이트
                console.log('🎯 자동생성 일정 확정 완료 - 백엔드에서 최신 데이터 가져오기');
                
                // 백엔드에서 최신 데이터를 가져와서 UI 업데이트
                await fetchGames();
                console.log('✅ 백엔드에서 최신 데이터 가져오기 완료');
                window.dispatchEvent(new CustomEvent('gamesChanged'));
          
          // SchedulePageV2에 경기 데이터 변경 알림
          if (onGameDataChanged) {
            onGameDataChanged();
          }
          
          // 모달 닫기
          onClose();
          
          // 성공 메시지
          toast({
            title: '경기 일정 확정 완료',
            description: result.emailNotification?.success
              ? '회원들에게 이메일 알림이 발송되었습니다.'
              : `일정은 확정됐지만 이메일은 발송되지 않았습니다. (${result.emailNotification?.reason || result.emailNotification?.error || '메일 설정 확인 필요'})`,
            status: result.emailNotification?.success ? 'success' : 'warning',
            duration: 5000,
            isClosable: true,
          });
          
          return; // 자동생성 경기 처리 완료
        }
        
        // 일반 경기 수정
        // 경기 수정 - 백엔드 API 호출
        const updatedFormData = {
          ...formData,
          // eventType이 null이거나 빈 값이면 기본값 설정
          eventType: formData.eventType || '자체',
          // selectedMembers는 별도로 저장하고, memberNames는 수기 입력만 포함
          memberNames: formData.memberNames.filter(name => name.trim() !== ''),
          selectedMembers: selectedMembers, // 선택된 회원을 별도 필드로 저장
          mercenaryCount: formData.mercenaryCount || 0,
          locationAddress: formData.locationAddress || '', // 주소 정보
          // 백엔드가 기대하는 gameType 보정
          gameType: (formData.eventType === '매치') ? 'MATCH' : 'SELF'
        };
        
        // 통일 유틸로 토큰 확보
        const token = getValidToken();

        if (!token) {
          toast({
            title: '인증 오류',
            description: '로그인이 필요합니다.',
            status: 'error',
            duration: 3000,
            isClosable: true,
          });
          return;
        }

        console.log('🔍 경기 수정 시도:', { 
          gameId: editingGame.id, 
          tokenLength: token.length,
          hasToken: !!token
        });

        // ID 형식 정리 - 최종 강력한 파싱
        let gameId: number;
        
        console.log('🔍 수정 원본 ID 분석:', { 
          originalId: editingGame.id, 
          type: typeof editingGame.id,
          stringValue: editingGame.id.toString()
        });
        
        if (typeof editingGame.id === 'number') {
          gameId = editingGame.id;
        } else {
          // 문자열인 경우 :1, :0 등 모든 접미사 제거 후 숫자만 추출
          let cleanIdStr = editingGame.id.toString();
          
          // :1, :0 등 콜론 접미사 제거
          if (cleanIdStr.includes(':')) {
            cleanIdStr = cleanIdStr.split(':')[0];
          }
          
          // 모든 비숫자 문자 제거
          cleanIdStr = cleanIdStr.replace(/[^0-9]/g, '');
          
          gameId = parseInt(cleanIdStr);
          
          console.log('🔧 수정 ID 파싱 과정:', {
            original: editingGame.id,
            afterColonRemoval: cleanIdStr,
            finalGameId: gameId
          });
        }
        
        // 유효한 ID인지 확인 (1-99999999 범위로 확장)
        if (isNaN(gameId) || gameId <= 0 || gameId > 99999999) {
          console.error('❌ 유효하지 않은 게임 ID:', { 
            originalId: editingGame.id, 
            type: typeof editingGame.id,
            gameId 
          });
          throw new Error(`유효하지 않은 게임 ID: ${editingGame.id}`);
        }
        
        console.log('✅ 최종 파싱된 수정 게임 ID:', { originalId: editingGame.id, gameId });
        
        // 실제 게임 객체에서 ID 재확인
        const actualGame = games.find(g => g.id === editingGame.id);
        if (actualGame) {
          console.log('🔍 실제 게임 객체 ID:', actualGame.id);
          // 실제 게임 객체의 ID가 다르면 그것을 사용
          if (typeof actualGame.id === 'number' && actualGame.id !== gameId) {
            console.log('⚠️ ID 불일치 감지, 실제 게임 ID 사용:', actualGame.id);
            gameId = actualGame.id;
          }
        }
        
        // DB에 존재하지 않는 임시 id면 생성(POST), 정수형 id면 수정(PUT)
        const gameIdStr = gameId.toString();
        const isPersistedId = typeof gameId === 'number' 
          && Number.isSafeInteger(gameId)
          && gameId > 0 
          && gameId < 1000000000 // 비정상적으로 큰 임시 ID(타임스탬프형) 방지
          && !gameIdStr.includes('.') // 소수점이 포함된 타임스탬프 ID 제외
          && gameIdStr.length < 10; // 타임스탬프는 보통 13자리 이상
        const requestUrl = await getApiUrl(
          isPersistedId ? `/games/${gameId}` : '/games'
        );
        const requestMethod = isPersistedId ? 'PUT' : 'POST';

        console.log('🔍 API 요청 정보:', {
          url: requestUrl,
          method: requestMethod,
          tokenLength: token.length,
          hasToken: !!token
        });

        const response = await fetch(requestUrl, {
          method: requestMethod,
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify({
            ...updatedFormData
          })
        });

        console.log('🔍 API 응답 상태:', response.status, response.statusText);

        if (!response.ok) {
          if (response.status === 401) {
            // 토큰 만료 또는 인증 실패
            toast({
              title: '인증 오류',
              description: '로그인이 만료되었습니다. 다시 로그인해주세요.',
              status: 'error',
              duration: 3000,
              isClosable: true,
            });
            // 로그아웃 처리
            localStorage.removeItem('token');
            localStorage.removeItem('auth_token_backup');
            sessionStorage.removeItem('token');
            window.location.href = '/login';
            return;
          }
          const errorText = await response.text();
          console.error('경기 수정 실패:', errorText);
          throw new Error(`경기 수정 실패: ${response.status} ${errorText}`);
        }

        const result = await response.json();
        console.log('경기 수정 성공:', result);
        
        // 자동생성 일정이 삭제되었는지 확인
        if (result.autoGeneratedGamesDeleted) {
          console.log('🎯 자동생성 일정이 삭제됨 - UI 새로고침 필요');
          // 페이지 전체 새로고침을 통해 모든 데이터 동기화
          setTimeout(() => {
            window.location.reload();
          }, 1000);
        } else {
          // 일반적인 경우에는 fetchGames 호출
          await fetchGames();
        }
        window.dispatchEvent(new CustomEvent('gamesChanged'));
        
        // SchedulePageV2에 경기 데이터 변경 알림
        if (onGameDataChanged) {
          onGameDataChanged();
        }
        
        // 자동생성된 게임이 확정된 경우 특별한 메시지 표시
        const isAutoGeneratedConfirmed = editingGame.autoGenerated && 
          formData.time && formData.location && formData.eventType &&
          formData.time !== '미정' && formData.location !== '미정';
        
        if (isAutoGeneratedConfirmed) {
          toast({
            title: '경기 일정 확정 완료',
            description: '회원들에게 알림이 발송되었습니다. 같은 주의 다른 자동생성된 일정들은 삭제되었습니다.',
            status: 'success',
            duration: 5000,
            isClosable: true,
          });
        } else {
          toast({
            title: '경기 수정 완료',
            description: '경기 정보가 수정되었습니다.',
            status: 'success',
            duration: 2000,
            isClosable: true,
          });
        }
      } else {
        // 새 경기 추가 - 백엔드 API 호출
        const newFormData = {
          ...formData,
          // eventType이 null이거나 빈 값이면 기본값 설정
          eventType: formData.eventType || '자체',
          // selectedMembers는 별도로 저장하고, memberNames는 수기 입력만 포함
          memberNames: formData.memberNames.filter(name => name.trim() !== ''),
          selectedMembers: selectedMembers, // 선택된 회원을 별도 필드로 저장
          locationAddress: formData.locationAddress || '', // 주소 정보
          createdById: 1,
          gameType: (formData.eventType === '매치') ? 'MATCH' : 'SELF'
        };
        
        // 토큰 가져오기 (여러 위치에서 시도)
        const token = getValidToken();
        
        if (!token) {
          toast({
            title: '인증 오류',
            description: '로그인이 필요합니다.',
            status: 'error',
            duration: 3000,
            isClosable: true,
          });
          return;
        }

        console.log('🔍 경기 추가 시도:', { tokenLength: token.length });

        const createUrl = await getApiUrl('/games');
        const response = await fetch(createUrl, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify(newFormData)
        });

        if (!response.ok) {
          throw new Error('경기 추가 실패');
        }
        
        const result = await response.json();
        console.log('경기 추가 성공:', result);
        
        // 자동생성 일정이 삭제되었는지 확인
        if (result.autoGeneratedGamesDeleted) {
          console.log('🎯 자동생성 일정이 삭제됨 - UI 새로고침 필요');
          // 페이지 전체 새로고침을 통해 모든 데이터 동기화
          setTimeout(() => {
            window.location.reload();
          }, 1000);
        }
        
        await fetchGames();
        window.dispatchEvent(new CustomEvent('gamesChanged'));
        
        // SchedulePageV2에 경기 데이터 변경 알림
        if (onGameDataChanged) {
          onGameDataChanged();
        }
        
        toast({
          title: '경기 추가 완료',
          description: '새 경기가 추가되었습니다.',
          status: 'success',
          duration: 2000,
          isClosable: true,
        });
      }

      onClose();
    } catch (error) {
      console.error('경기 저장 오류:', error);
      const errorMessage = error instanceof Error ? error.message : '알 수 없는 오류가 발생했습니다.';
      toast({
        title: '저장 실패',
        description: `경기 정보 저장 중 오류가 발생했습니다: ${errorMessage}`,
        status: 'error',
        duration: 5000,
        isClosable: true,
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const getEventTypeName = (type: string) => {
    switch (type) {
      case '자체': return '자체';
      case '매치': return '매치';
      case '회식': return '회식';
      default: return '자체';
    }
  };

  // ── 표시 전용 파생 값 (filteredGames 그대로 사용, fetch/API 변경 없음) ──
  const todayMs = new Date(new Date().setHours(0, 0, 0, 0)).getTime();
  const participantCountOf = (game: Game) => (game as Game & { totalParticipantCount?: number }).totalParticipantCount ?? 0;
  const upcomingGames = filteredGames
    .filter(g => parseGameDateMs(g) >= todayMs)
    .sort((a, b) => parseGameDateMs(a) - parseGameDateMs(b));
  const pastGames = filteredGames.filter(g => parseGameDateMs(g) < todayMs); // 기존 정렬(최신순) 유지
  const pendingCount = filteredGames.filter(g => g.autoGenerated).length;
  const nowDate = new Date();
  const thisMonthCount = filteredGames.filter(g => {
    const d = new Date(parseGameDateMs(g));
    return !g.autoGenerated && d.getFullYear() === nowDate.getFullYear() && d.getMonth() === nowDate.getMonth();
  }).length;
  const nextGame = upcomingGames[0] || null;
  const nextGameDDay = nextGame ? Math.round((parseGameDateMs(nextGame) - todayMs) / 86400000) : null;
  const WEEKDAYS_KO = ['일', '월', '화', '수', '목', '금', '토'];
  const MONTHS_EN = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];
  const timeLabel = (game: Game) => (game.autoGenerated ? '미정' : game.time || '시간 미정');
  const locationLabel = (game: Game) => (game.autoGenerated ? '미정' : game.location || '-');
  const creatorLabel = (game: Game) => game.createdBy?.name
    || (userList.find((u: any) => u.id === game.createdById)?.name)
    || '알 수 없음';

  // 작은 날짜 칩: OCT / 05 / (월)
  const renderMiniDate = (game: Game, isPast: boolean) => {
    const d = new Date(parseGameDateMs(game));
    return (
      <Box textAlign="center" minW="48px" py={1} borderRadius="md" bg={isPast ? 'gray.50' : 'brand.50'} flexShrink={0}>
        <Text textStyle="scoreLabel" fontSize="9px" color={isPast ? 'gray.400' : 'brand.500'}>{MONTHS_EN[d.getMonth()]}</Text>
        <Text textStyle="statNumber" fontSize="24px" color={isPast ? 'gray.500' : 'matchday.navy'}>{String(d.getDate()).padStart(2, '0')}</Text>
        <Text fontSize="10px" fontWeight="700" color={d.getDay() === 0 ? 'red.400' : d.getDay() === 6 ? 'brand.400' : 'gray.400'}>{WEEKDAYS_KO[d.getDay()]}</Text>
      </Box>
    );
  };

  const renderEventBadge = (game: Game) => (
    game.autoGenerated
      ? <StatusBadge kind="eventType" value="미정" />
      : <StatusBadge kind="eventType" value={getEventTypeName(game.eventType || '자체')} />
  );

  const renderActions = (game: Game, size: 'sm' | 'md') => (
    <HStack spacing={1} justify="flex-end">
      {game.autoGenerated ? (
        <Button size={size === 'md' ? 'sm' : 'xs'} bg="matchday.volt" color="matchday.navy" fontWeight="800" _hover={{ opacity: 0.85 }} leftIcon={<Icon as={LuCalendarCheck} />} onClick={() => handleEditGame(game)}>
          일정확정
        </Button>
      ) : (
        <Tooltip label="경기 수정" placement="top" hasArrow bg="matchday.navy" color="white" fontSize="sm">
          <IconButton aria-label="경기 수정" icon={<Icon as={LuPencil} />} size={size} variant="ghost" color="brand.500" onClick={() => handleEditGame(game)} />
        </Tooltip>
      )}
      <Tooltip label="경기 삭제" placement="top" hasArrow bg="red.600" color="white" fontSize="sm">
        <IconButton
          aria-label="경기 삭제"
          icon={<Icon as={LuTrash2} />}
          size={size}
          variant="ghost"
          color="red.500"
          _hover={{ bg: 'red.50' }}
          onClick={() => {
            setDeleteTarget(game);
            onDeleteOpen();
          }}
        />
      </Tooltip>
    </HStack>
  );

  const renderGameList = (list: Game[], isPast: boolean) => (
    <>
      {/* 데스크톱: 테이블 */}
      <TableContainer display={{ base: 'none', md: 'block' }}>
        {/* 예정·지난 경기 표의 열이 같은 위치에 오도록 고정 폭 */}
        <Table variant="simple" size="sm" sx={{ tableLayout: 'fixed' }}>
          <Thead>
            <Tr>
              {([['일시', '24%'], ['장소', 'auto'], ['유형', '10%'], ['인원', '10%'], ['생성자', '12%']] as const).map(([h, w]) => (
                <Th key={h} w={w} textStyle="scoreLabel" fontSize="10px" color="gray.500" py={3}>{h}</Th>
              ))}
              {/* 작업 열 pr: desktop(lg+) 우하단 챗봇 버튼(right 24px + 48px)과 겹치지 않도록 이 열에만 여백 */}
              <Th w="18%" textStyle="scoreLabel" fontSize="10px" color="gray.500" py={3} textAlign="right" pr={{ base: 4, lg: 12 }}>작업</Th>
            </Tr>
          </Thead>
          <Tbody>
            {list.map(game => (
              <Tr key={game.id} bg={game.autoGenerated ? 'rgba(215,255,58,.10)' : 'transparent'} _hover={{ bg: game.autoGenerated ? 'rgba(215,255,58,.18)' : 'gray.50' }}>
                <Td py={2.5}>
                  <Flex align="center" gap={3}>
                    {renderMiniDate(game, isPast)}
                    <Box>
                      <Text fontWeight="700" color={isPast ? 'gray.500' : 'matchday.navy'} sx={{ fontVariantNumeric: 'tabular-nums' }}>{timeLabel(game)}</Text>
                      {game.autoGenerated && <Box mt={1}><StatusBadge kind="pending" value="PENDING" /></Box>}
                    </Box>
                  </Flex>
                </Td>
                <Td py={2.5}><Text fontSize="sm" color={isPast ? 'gray.500' : 'gray.700'} noOfLines={1}>{locationLabel(game)}</Text></Td>
                <Td py={2.5}>{renderEventBadge(game)}</Td>
                <Td py={2.5}>
                  <Text as="span" fontFamily="display" fontWeight="700" fontSize="lg" color={isPast ? 'gray.500' : 'matchday.navy'} sx={{ fontVariantNumeric: 'tabular-nums' }}>{participantCountOf(game)}</Text>
                  <Text as="span" fontSize="xs" color="gray.500" ml={0.5}>명</Text>
                </Td>
                <Td py={2.5}><Text fontSize="sm" color="gray.500">{creatorLabel(game)}</Text></Td>
                <Td py={2.5} pr={{ base: 4, lg: 12 }}>{renderActions(game, 'sm')}</Td>
              </Tr>
            ))}
          </Tbody>
        </Table>
      </TableContainer>

      {/* 모바일: 카드 리스트 */}
      <VStack display={{ base: 'flex', md: 'none' }} spacing={0} align="stretch" divider={<Box borderBottom="1px solid" borderColor="gray.100" />}>
        {list.map(game => (
          <Box key={game.id} px={4} py={3.5} bg={game.autoGenerated ? 'rgba(215,255,58,.10)' : 'transparent'}>
            <Flex gap={3} align="flex-start">
              {renderMiniDate(game, isPast)}
              <Box flex={1} minW={0}>
                <Flex justify="space-between" align="center" gap={2}>
                  <Text fontWeight="800" color={isPast ? 'gray.500' : 'matchday.navy'} sx={{ fontVariantNumeric: 'tabular-nums' }}>{timeLabel(game)}</Text>
                  <HStack spacing={1.5}>
                    {game.autoGenerated && <StatusBadge kind="pending" value="PENDING" />}
                    {renderEventBadge(game)}
                  </HStack>
                </Flex>
                <HStack spacing={1.5} mt={1} color="gray.500" fontSize="sm">
                  <Icon as={LuMapPin} boxSize={3.5} flexShrink={0} />
                  <Text noOfLines={1}>{locationLabel(game)}</Text>
                </HStack>
                <Flex justify="space-between" align="center" mt={1.5}>
                  <HStack spacing={1.5} color="gray.500" fontSize="sm" minW={0} flex={1} mr={2}>
                    <Icon as={LuUsers} boxSize={3.5} flexShrink={0} />
                    <Text noOfLines={1}><Text as="span" fontFamily="display" fontWeight="700" color={isPast ? 'gray.500' : 'matchday.navy'}>{participantCountOf(game)}</Text>명 · {creatorLabel(game)}</Text>
                  </HStack>
                  {/* pr: 관리자 모바일 챗봇 edge dock(우측 38px)과 겹치지 않게 */}
                  <Box flexShrink={0} pr={{ base: 3, lg: 0 }}>{renderActions(game, 'md')}</Box>
                </Flex>
              </Box>
            </Flex>
          </Box>
        ))}
      </VStack>
    </>
  );

  return (
    <>
      <VStack className="fccg-matchday fccg-admin" spacing={5} align="stretch">
        <AdminPageHeader
          eyebrow="MATCH OPERATIONS"
          title="경기 관리"
          description="경기 일정과 참가 현황을 관리합니다."
          right={
            <Button size="sm" bg="brand.500" color="white" _hover={{ bg: 'brand.600' }} leftIcon={<Icon as={LuCalendarPlus} />} onClick={handleAddGame}>
              경기 추가
            </Button>
          }
        />

        {/* NEXT MATCH HERO */}
        <Box
          position="relative"
          overflow="hidden"
          borderRadius="xl"
          bgGradient={nextGameDDay === 0 ? GRADIENTS.NEXT_MATCH_MATCHDAY : GRADIENTS.NEXT_MATCH_DEFAULT}
          color="white"
          p={{ base: 5, md: 6 }}
          boxShadow={nextGameDDay === 0 ? '0 0 0 2px #D7FF3A' : 'none'}
        >
          <PitchLines opacity={0.08} />
          <Flex position="relative" justify="space-between" align="center" mb={5} gap={2}>
            <Text textStyle="scoreLabel" color="whiteAlpha.800">{nextGameDDay === 0 ? 'MATCH DAY' : 'NEXT MATCH'}</Text>
            {nextGameDDay !== null && (
              nextGameDDay === 0 ? (
                <HStack spacing={1.5} bg="matchday.volt" px={2.5} py={1} borderRadius="sm">
                  <LiveDot color="matchday.navy" />
                  <Text textStyle="scoreLabel" color="matchday.navy">TODAY</Text>
                </HStack>
              ) : (
                <Box border="1px solid" borderColor="whiteAlpha.500" px={2.5} py={1} borderRadius="sm">
                  <Text textStyle="scoreLabel" color="white">D-{nextGameDDay}</Text>
                </Box>
              )
            )}
          </Flex>

          {nextGame ? (
            <Flex position="relative" direction={{ base: 'column', sm: 'row' }} gap={{ base: 4, md: 6 }} align={{ base: 'stretch', sm: 'center' }}>
              <DateBlock date={new Date(parseGameDateMs(nextGame))} alignSelf={{ base: 'flex-start', sm: 'center' }} />
              <Box flex={1} minW={0}>
                <Text textStyle="scoreLabel" color="whiteAlpha.700">KICK OFF</Text>
                <Text textStyle="statNumber" fontSize={{ base: '52px', md: '68px' }} mt={1}>
                  {nextGame.time && nextGame.time !== '미정' && !nextGame.autoGenerated ? nextGame.time : 'TBD'}
                </Text>
                <HStack spacing={2} mt={3} flexWrap="wrap">
                  {renderEventBadge(nextGame)}
                  {nextGame.autoGenerated && <StatusBadge kind="pending" value="PENDING" />}
                </HStack>
                <VStack align="stretch" spacing={1.5} mt={4} fontSize="sm" color="whiteAlpha.900">
                  <HStack spacing={2}>
                    <Icon as={LuMapPin} boxSize={4} color="whiteAlpha.700" flexShrink={0} />
                    <Text noOfLines={1}>{nextGame.autoGenerated || !nextGame.location ? '장소 미정' : nextGame.location}</Text>
                  </HStack>
                  <HStack spacing={2}>
                    <Icon as={LuUsers} boxSize={4} color="whiteAlpha.700" flexShrink={0} />
                    <Text><Text as="span" fontFamily="display" fontWeight="700" fontSize="lg" sx={{ fontVariantNumeric: 'tabular-nums' }}>{participantCountOf(nextGame)}</Text>명 참가</Text>
                  </HStack>
                </VStack>
              </Box>
              <Box minW={{ sm: '140px' }}>
                {nextGame.autoGenerated ? (
                  <Button w="100%" size="sm" bg="matchday.volt" color="matchday.navy" fontWeight="800" _hover={{ opacity: 0.9 }} leftIcon={<Icon as={LuCalendarCheck} />} onClick={() => handleEditGame(nextGame)}>
                    일정확정
                  </Button>
                ) : (
                  <Button w="100%" size="sm" bg="white" color="brand.600" _hover={{ bg: 'whiteAlpha.900' }} leftIcon={<Icon as={LuPencil} />} onClick={() => handleEditGame(nextGame)}>
                    경기 수정
                  </Button>
                )}
              </Box>
            </Flex>
          ) : (
            <Flex position="relative" direction={{ base: 'column', sm: 'row' }} align={{ base: 'flex-start', sm: 'center' }} justify="space-between" gap={4} py={{ base: 2, md: 4 }}>
              <Box>
                <Text fontFamily="display" fontWeight="700" fontSize={{ base: '30px', md: '40px' }} lineHeight="1" textTransform="uppercase">No match scheduled</Text>
                <Text fontSize="sm" color="whiteAlpha.800" mt={2}>예정된 경기가 없습니다. 다음 경기를 등록해 주세요.</Text>
              </Box>
              <Button size="md" bg="matchday.volt" color="matchday.navy" _hover={{ opacity: 0.9 }} leftIcon={<Icon as={LuCalendarPlus} />} onClick={handleAddGame}>
                경기 등록하기
              </Button>
            </Flex>
          )}
        </Box>

        <StatStrip columns={3}>
          <StatBlock compact label="UPCOMING" caption="예정 경기" value={upcomingGames.length} unit="경기" />
          <StatBlock compact label="PENDING" caption="확정 필요" value={pendingCount} unit="건" highlight={pendingCount > 0} />
          <StatBlock compact label="THIS MONTH" caption="이번 달 확정 경기" value={thisMonthCount} unit="경기" />
        </StatStrip>

        {games?.length === 0 ? (
          <AdminPanel>
            <AdminEmptyState
              icon={LuCalendarX}
              title="등록된 경기가 없습니다"
              description="새 경기를 추가해 일정을 관리해 보세요."
              action={<Button size="sm" bg="brand.500" color="white" _hover={{ bg: 'brand.600' }} leftIcon={<Icon as={LuCalendarPlus} />} onClick={handleAddGame}>경기 추가</Button>}
            />
          </AdminPanel>
        ) : (
          <>
            <AdminPanel p={0} overflow="hidden">
              <Box px={{ base: 4, md: 6 }} pt={{ base: 4, md: 5 }}>
                <PanelHeader label="UPCOMING" title="예정 경기" right={<Text textStyle="scoreLabel" color="gray.400">{upcomingGames.length} GAMES</Text>} />
              </Box>
              {upcomingGames.length > 0 ? renderGameList(upcomingGames, false) : (
                <Text fontSize="sm" color="gray.500" px={{ base: 4, md: 6 }} pb={5}>예정된 경기가 없습니다.</Text>
              )}
            </AdminPanel>

            {pastGames.length > 0 && (
              <AdminPanel p={0} overflow="hidden">
                <Box px={{ base: 4, md: 6 }} pt={{ base: 4, md: 5 }}>
                  <PanelHeader label="ARCHIVE" title="지난 경기" right={<Text textStyle="scoreLabel" color="gray.400">{pastGames.length} GAMES</Text>} />
                </Box>
                {renderGameList(pastGames, true)}
              </AdminPanel>
            )}
          </>
        )}
      </VStack>

      {/* 경기 추가/수정 모달 */}
      <Modal isOpen={isOpen} onClose={onClose} motionPreset="slideInBottom" scrollBehavior="inside">
        <ModalOverlay />
        <ModalContent maxW={{ base: 'calc(100% - 32px)', md: '560px' }} className="fccg-admin">
          <ModalHeader py={4} color="matchday.navy" fontWeight="800">
            {editingGame ? (editingGame.autoGenerated ? '일정확정' : '경기 수정') : '경기 추가'}
          </ModalHeader>
          <ModalCloseButton />
          <ModalBody pb={4}>
            <VStack spacing={2}>
              {/* 날짜와 이벤트 유형을 같은 행에 배치하되 y축 위치는 장소, 인원관리와 맞춤 */}
              <FormControl>
                <FormLabel>일시 & 이벤트</FormLabel>
                <Stack direction={{ base: 'column', md: 'row' }} spacing={2} align="stretch">
                  <Input
                    type="date"
                    value={formData.date}
                    onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                    size="sm"
                    h="36px"
                    flex={1}
                    minW={{ md: '200px' }}
                  />
                  <Select
                    value={formData.time || ''}
                    onChange={(e) => setFormData({ ...formData, time: e.target.value })}
                    placeholder="시간"
                    size="sm"
                    h="36px"
                    w={{ base: '100%', md: '120px' }}
                  >
                    <option value="18:00">오후 6:00</option>
                    <option value="18:30">오후 6:30</option>
                    <option value="19:00">오후 7:00</option>
                    <option value="19:30">오후 7:30</option>
                    <option value="20:00">오후 8:00</option>
                    <option value="20:30">오후 8:30</option>
                  </Select>
                  <Select
                    value={formData.eventType}
                    onChange={(e) => setFormData({ ...formData, eventType: e.target.value as '매치' | '회식' | '자체' })}
                    size="sm"
                    h="36px"
                    w={{ base: '100%', md: '100px' }}
                  >
                    <option value="자체">자체</option>
                    <option value="매치">매치</option>
                    <option value="회식">회식</option>
                  </Select>
                </Stack>
              </FormControl>
              
              <FormControl>
                <FormLabel>장소</FormLabel>
                <VStack spacing={2} align="stretch">
                  <HStack>
                    <Input
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      placeholder="장소명을 검색하세요"
                      onKeyPress={(e) => e.key === 'Enter' && searchLocation(searchQuery)}
                    />
                    <Button
                      onClick={() => searchLocation(searchQuery)}
                      isLoading={isSearching}
                      colorScheme="blue"
                      size="sm"
                    >
                      검색
                    </Button>
                  </HStack>
                  
                  {/* 검색 결과 */}
                  {showSearchResults && searchResults.length > 0 && (
                    <Box
                      border="1px solid"
                      borderColor="gray.200"
                      borderRadius="md"
                      maxH="200px"
                      overflowY="auto"
                      bg="white"
                      zIndex={10}
                    >
                      {searchResults.map((place, index) => (
                        <Box
                          key={index}
                          p={3}
                          borderBottom="1px solid"
                          borderColor="gray.100"
                          cursor="pointer"
                          _hover={{ bg: "gray.50" }}
                          onClick={() => selectLocation(place)}
                        >
                          <Text fontWeight="bold" fontSize="sm">{place.place_name}</Text>
                          <Text fontSize="xs" color="gray.600" mt={1}>
                            {place.road_address_name || place.address_name}
                          </Text>
                        </Box>
                      ))}
                    </Box>
                  )}
                  
                  {/* 장소명 */}
                  <Box>
                    <Text fontSize="xs" color="gray.600" mb={1} fontWeight="medium">장소명</Text>
                    <Input
                      value={formData.locationBase}
                      onChange={(e) => {
                        const baseLocation = e.target.value;
                        setFormData(prev => ({
                          ...prev,
                          locationBase: baseLocation,
                          location: baseLocation + (prev.locationDetail ? ` ${prev.locationDetail}` : '')
                        }));
                      }}
                      placeholder="장소명을 검색하거나 직접 입력"
                    />
                  </Box>
                  
                  {/* 주소 */}
                  <Box>
                    <Text fontSize="xs" color="gray.600" mb={1} fontWeight="medium">주소</Text>
                    <Input
                      value={formData.locationAddress}
                      onChange={(e) => {
                        setFormData(prev => ({
                          ...prev,
                          locationAddress: e.target.value
                        }));
                      }}
                      placeholder="주소가 자동으로 입력됩니다"
                      readOnly
                      bg="gray.50"
                    />
                  </Box>
                  
                  {/* 세부 장소 */}
                  <Box>
                    <Text fontSize="xs" color="gray.600" mb={1} fontWeight="medium">세부 장소</Text>
                    <Input
                      value={formData.locationDetail}
                      onChange={(e) => {
                        const detail = e.target.value;
                        setFormData(prev => ({
                          ...prev,
                          locationDetail: detail,
                          location: prev.locationBase + (detail ? ` ${detail}` : '')
                        }));
                      }}
                      placeholder="세부 장소 (예: 1구장, 2구장 등)"
                    />
                  </Box>
                </VStack>
              </FormControl>
              

              

              
                            {/* 인원 관리 - 좌우 병기 */}
              <FormControl>
                <Flex justify="space-between" align={{ base: 'flex-start', md: 'center' }} direction={{ base: 'column', md: 'row' }} gap={1} mb={2}>
                  <FormLabel mb={0}>확정 참가자 관리</FormLabel>
                  <Box>
                    <Text fontSize="sm" fontWeight="bold" color="brand.500">
                      전체 인원: {getTotalCount()}명 (회원 {getUniqueMemberCount()}명 + 용병 {formData.mercenaryCount}명 + 수기입력 {formData.memberNames.filter(name => name.trim() !== '').length}명)
                    </Text>
                  </Box>
                </Flex>
                <Stack direction={{ base: 'column', md: 'row' }} spacing={4} align="stretch">
                  {/* 왼쪽: 회원 선택 */}
                  <Box flex={1}>
                    <Text fontSize="sm" color="gray.600" mb={1} fontWeight="bold">확정 참가 회원</Text>
                    <Text fontSize="xs" color="gray.500" mb={2}>투표 결과와 별개로 이 명단이 확정 일정과 메인 화면에 표시됩니다.</Text>
                    <Box>
                      {userList.map((user) => {
                        const isSelected = selectedMembers.includes(user.name);
                        return (
                          <Button
                            key={user.id}
                            size="xs"
                            fontSize="xs"
                            borderRadius="full"
                            h="28px"
                            px={3}
                            mr={2}
                            mb={2}
                            bg={isSelected ? brandBlue : 'white'}
                            color={isSelected ? 'white' : brandBlue}
                            borderColor={brandBlue}
                            borderWidth="1px"
                            _hover={{
                              bg: isSelected ? '#003d7a' : 'rgba(0, 78, 168, 0.08)',
                              color: isSelected ? 'white' : brandBlue
                            }}
                            onClick={() => {
                              if (isSelected) {
                                setSelectedMembers(prev => prev.filter(name => name !== user.name));
                              } else {
                                setSelectedMembers(prev => [...prev, user.name]);
                              }
                            }}
                          >
                            {user.name}
                          </Button>
                        );
                      })}
                    </Box>
 
                  </Box>
 
                   {/* 오른쪽: 용병 및 수기 입력을 1행 2열로 재분할 */}
                   <Box flex={1}>
                     <Text fontSize="sm" color="gray.600" mb={1} fontWeight="bold">용병 & 수기 입력</Text>
                     <HStack spacing={3} align="flex-start">
                       {/* 용병 입력 부분 */}
                       <Box flex={1}>
                         <Text fontSize="xs" color="gray.500" mb={1}>용병 인원</Text>
                         <Input
                           type="number"
                           value={formData.mercenaryCount}
                           onChange={(e) => setFormData({ ...formData, mercenaryCount: parseInt(e.target.value) || 0 })}
                           placeholder="0"
                           min="0"
                           size="sm"
                           h="32px"
                         />
                       </Box>
 
                       {/* 수기 입력 부분 */}
                       <Box flex={1}>
                         <Text fontSize="xs" color="gray.500" mb={1}>수기 입력</Text>
                         {formData.memberNames.map((name, index) => (
                           <HStack key={index} mb={1} align="center">
                             <Input
                               value={name}
                               onChange={(e) => updateMemberName(index, e.target.value)}
                               placeholder={`팀원 ${index + 1} 이름`}
                               size="sm"
                               h="32px"
                             />
                             {formData.memberNames.length > 1 && (
                               <IconButton
                                 aria-label="수기 입력 삭제"
                                 size="sm"
                                 icon={<DeleteIcon boxSize={3} />}
                                 colorScheme="red"
                                 variant="ghost"
                                 onClick={() => removeMemberName(index)}
                               />
                             )}
                           </HStack>
                         ))}
                         <Button
                           size="sm"
                           colorScheme="blue"
                           variant="outline"
                           onClick={addMemberName}
                           leftIcon={<AddIcon />}
                           w="100%"
                           mt={1}
                         >
                           팀원 추가
                         </Button>
                       </Box>
                     </HStack>
                   </Box>
                </Stack>
              </FormControl>
              

              
              {/* 자동생성된 경기일 때만 표시되는 일정확정 안내 (확정 버튼은 하단 footer) */}
              {editingGame && editingGame.autoGenerated === true && (
                <Box
                  w="100%"
                  mt={2}
                  p={4}
                  bg="matchday.navy"
                  color="white"
                  borderRadius="lg"
                  borderLeft="4px solid"
                  borderLeftColor="matchday.volt"
                >
                  <Text textStyle="scoreLabel" fontSize="10px" color="matchday.volt">PENDING CONFIRMATION</Text>
                  <Text fontSize="md" fontWeight="bold" mt={1.5} mb={1}>
                    이 게임을 최종 확정하시겠습니까?
                  </Text>
                  <Text fontSize="sm" color="whiteAlpha.800">
                    확정 시 회원들에게 알림이 발송되고, 같은 주의 다른 자동생성된 일정들은 삭제됩니다.
                  </Text>
                </Box>
              )}
            </VStack>
          </ModalBody>
          <ModalFooter gap={3} borderTop="1px solid" borderColor="gray.100">
            {editingGame && editingGame.autoGenerated === true ? (
              <>
                <Button variant="ghost" color="gray.600" onClick={onClose} isDisabled={isSubmitting}>
                  취소
                </Button>
                <Button
                  bg="matchday.volt"
                  color="matchday.navy"
                  fontWeight="800"
                  _hover={{ opacity: 0.9 }}
                  leftIcon={<Icon as={LuCalendarCheck} />}
                  onClick={handleSubmit}
                  isLoading={isSubmitting}
                  loadingText="확정 중..."
                >
                  일정확정
                </Button>
              </>
            ) : (
              <>
                <Button variant="ghost" color="gray.600" onClick={onClose} isDisabled={isSubmitting}>
                  취소
                </Button>
                <Button
                  bg="brand.500"
                  color="white"
                  _hover={{ bg: 'brand.600' }}
                  onClick={handleSubmit}
                  isLoading={isSubmitting}
                  loadingText={editingGame ? '수정 중...' : '추가 중...'}
                >
                  {editingGame ? '수정' : '추가'}
                </Button>
              </>
            )}
          </ModalFooter>
        </ModalContent>
      </Modal>

      {/* 경기 삭제 확인 모달 */}
      <Modal isOpen={isDeleteOpen} onClose={() => !isDeleting && onDeleteClose()}>
        <ModalOverlay />
        <ModalContent mx={4} className="fccg-admin">
          <ModalHeader color="matchday.navy" fontWeight="800">경기 삭제 확인</ModalHeader>
          <ModalBody>
            {deleteTarget && (
              <VStack align="stretch" spacing={3}>
                <Box p={3} bg="gray.50" borderRadius="md" border="1px solid" borderColor="gray.200">
                  <Text fontSize="sm" fontWeight="bold" color="gray.800">
                    {(() => {
                      const d = new Date(deleteTarget.date);
                      const weekdays = ['일', '월', '화', '수', '목', '금', '토'];
                      return `${d.getFullYear()}.${String(d.getMonth() + 1).padStart(2, '0')}.${String(d.getDate()).padStart(2, '0')}.(${weekdays[d.getDay()]})`;
                    })()}
                  </Text>
                  <Text fontSize="sm" color="gray.600">
                    {deleteTarget.autoGenerated ? '미정' : deleteTarget.location}
                  </Text>
                </Box>
                <Text fontSize="sm" color="gray.700">
                  이 경기를 삭제하면 연결된 참가/출석 기록도 함께 삭제됩니다. 이 작업은 되돌릴 수 없습니다.
                </Text>
              </VStack>
            )}
          </ModalBody>
          <ModalFooter gap={3} borderTop="1px solid" borderColor="gray.100" mt={4}>
            <Button variant="ghost" color="gray.600" onClick={onDeleteClose} isDisabled={isDeleting}>
              취소
            </Button>
            <Button colorScheme="red" onClick={handleConfirmDeleteGame} isLoading={isDeleting} loadingText="삭제 중...">
              삭제
            </Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </>
  );
}
