-- 프로덕션 데이터베이스 초기화 SQL
-- Neon SQL Editor에서 실행하세요

-- 1. 사용자 데이터 (비밀번호: password123)
INSERT INTO "User" (id, email, password, name, role, status, "createdAt", "updatedAt") 
VALUES (1, 'sti60val@gmail.com', '$2b$10$/TNmVeS8a5Hb/eYdBISSo.uONXVDh6r6rjCV0RPejaRoV.0MvxvHm', '정성인', 'SUPER_ADMIN', 'ACTIVE', now(), now())
ON CONFLICT (email) DO UPDATE SET 
  password = '$2b$10$/TNmVeS8a5Hb/eYdBISSo.uONXVDh6r6rjCV0RPejaRoV.0MvxvHm',
  role = 'SUPER_ADMIN',
  status = 'ACTIVE';

-- 2. 현재 주 투표 세션 (11월 3일-7일)
INSERT INTO "VoteSession" (id, "weekStartDate", "startTime", "endTime", "isActive", "isCompleted", "createdAt", "updatedAt")
VALUES (1, '2025-11-03 00:00:00', '2025-11-02 00:00:00', '2025-11-06 23:59:59', true, false, now(), now())
ON CONFLICT (id) DO NOTHING;

-- 3. 지난 주 투표 세션 (10월 27일-31일) - 완료됨
INSERT INTO "VoteSession" (id, "weekStartDate", "startTime", "endTime", "isActive", "isCompleted", "createdAt", "updatedAt")
VALUES (2, '2025-10-27 00:00:00', '2025-10-26 00:00:00', '2025-10-30 23:59:59', false, true, now(), now())
ON CONFLICT (id) DO NOTHING;

-- 4. 지난 주 투표 데이터 (목, 금)
INSERT INTO "Vote" (id, "userId", "voteSessionId", "selectedDays", "createdAt", "updatedAt")
VALUES (1, 1, 2, '["THU","FRI"]', now(), now())
ON CONFLICT (id) DO NOTHING;

-- 5. 현재 주 투표 데이터 (수, 금)
INSERT INTO "Vote" (id, "userId", "voteSessionId", "selectedDays", "createdAt", "updatedAt")
VALUES (2, 1, 1, '["WED","FRI"]', now(), now())
ON CONFLICT (id) DO NOTHING;

-- 6. 지난 주 경기 데이터 (10월 30일) - 정규화된 값 사용
INSERT INTO "Game" (id, date, time, location, "gameType", "eventType", "memberNames", "selectedMembers", "mercenaryCount", "autoGenerated", confirmed, "createdById", "createdAt", "updatedAt")
VALUES (1, '2025-10-30 12:00:00', '19:00', '풋살장', 'MATCH', '매치', '["정성인"]', '["정성인"]', 0, false, true, 1, now(), now())
ON CONFLICT (id) DO UPDATE SET "eventType" = '매치', "gameType" = 'MATCH';

-- 완료 확인
SELECT '초기화 완료' as status;

