-- 사용자 데이터 (이미 있으면 스킵)
INSERT OR IGNORE INTO User (id, email, password, name, role, status, createdAt, updatedAt) 
VALUES (1, 'sti60val@gmail.com', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '정성인', 'SUPER_ADMIN', 'ACTIVE', datetime('now'), datetime('now'));

-- 현재 주 투표 세션 (10월 13일-17일)
INSERT INTO VoteSession (id, weekStartDate, startTime, endTime, isActive, isCompleted, createdAt, updatedAt)
VALUES (1, '2025-10-13 00:00:00', '2025-10-06 00:00:00', '2025-10-09 23:59:59', 1, 0, datetime('now'), datetime('now'));

-- 지난 주 투표 세션 (10월 6일-10일)
INSERT INTO VoteSession (id, weekStartDate, startTime, endTime, isActive, isCompleted, createdAt, updatedAt)
VALUES (2, '2025-10-06 00:00:00', '2025-10-05 00:00:00', '2025-10-10 23:59:59', 0, 1, datetime('now'), datetime('now'));

-- 지난 주 투표 데이터 (월, 수, 금)
INSERT INTO Vote (id, userId, voteSessionId, selectedDays, createdAt, updatedAt)
VALUES (1, 1, 2, '["MON","WED","FRI"]', datetime('now'), datetime('now'));

-- 현재 주 투표 데이터 (수, 금)
INSERT INTO Vote (id, userId, voteSessionId, selectedDays, createdAt, updatedAt)
VALUES (2, 1, 1, '["WED","FRI"]', datetime('now'), datetime('now'));

-- 지난 주 경기 데이터 (10월 8일)
INSERT INTO Game (id, date, time, location, gameType, eventType, memberNames, selectedMembers, mercenaryCount, autoGenerated, confirmed, createdById, createdAt, updatedAt)
VALUES (1, '2025-10-08 12:00:00', '19:00', '풋살장', 'FRIENDLY', '풋살', '["정성인"]', '["정성인"]', 0, 0, 1, 1, datetime('now'), datetime('now'));

